### PR TITLE
docs: add markdown plugin to README

### PR DESCRIPTION
**Pull request by SohamRatnaparkhi**
gh - #11 
I have added a link to `Chrome markdown-plugin` in `README.md` as stated in the issue.

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Thanks for the PR. I would not add the mention to this list which has to do with the libraries that power Papyrs - i.e. needed for the platform and app.

Maybe something like on this screenshot or any other idea?

Capture d’écran 2022-05-17 à 06 46 44

**Comment by SohamRatnaparkhi** [comment]
> Thanks for the PR. I would not add the mention to this list which has to do with the libraries that power Papyrs - i.e. needed for the platform and app.
> 
> Maybe something like on this screenshot or any other idea?
> 
> Capture d’écran 2022-05-17 à 06 46 44
Okay sure👍


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by SohamRatnaparkhi** [comment]
image
----
I have added a commit in this PR(#12 )
Now that part of README will look like the above image. Is it fine now or is any change required?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by peterpeterparker** [comment]
Super, thx 👍

**Pull request merged**
