### PR TITLE
Create zh-cn.json

### PR DESCRIPTION
**Pull request by bytesun**
simple Chinese translation

### CODE REVIEW

**Comment by peterpeterparker** [comment]
So cool!!!! Thanks a lot @bytesun 🙏

If you've got few more minutes, can you also translate the file for the library https://github.com/papyrs/stylo/blob/main/src/assets/i18n/en.ts ?

**Comment by bytesun** [comment]
yes, here is https://github.com/papyrs/stylo/pull/118

**Comment by peterpeterparker** [comment]
Super cool, it's live!

Thanks a lot @bytesun 🙏

**Review by NeutronStarPRO — COMMENTED** [review]
image
这里有一处需要更改，请改为 “ 直到 ”

**Pull request merged**
